version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 415552224382.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t 415552224382.dkr.ecr.ap-south-1.amazonaws.com/flasklambda .
      - docker push 415552224382.dkr.ecr.ap-south-1.amazonaws.com/flasklambda

artifacts:
  files: '**/*'
  name: imagedefinitions.json

cache:
  paths: []

